eclipse-platform/eclipse.platform.text

org.eclipse.jface.text.tests/META-INF/MANIFEST.MF
org.eclipse.jface.text.tests/pom.xml
org.eclipse.jface.text.tests/src/org/eclipse/jface/text/tests/TextPresentationTest.java
org.eclipse.jface.text.tests/src/org/eclipse/jface/text/tests/codemining/CodeMiningProjectionViewerTest.java
org.eclipse.jface.text.tests/src/org/eclipse/jface/text/tests/contentassist/AbstractContentAssistTest.java
org.eclipse.jface.text.tests/src/org/eclipse/jface/text/tests/contentassist/AsyncContentAssistTest.java
org.eclipse.jface.text.tests/src/org/eclipse/jface/text/tests/contentassist/ContextInformationPresenterTest.java
org.eclipse.jface.text.tests/src/org/eclipse/jface/text/tests/contentassist/ContextInformationTest.java
org.eclipse.jface.text.tests/src/org/eclipse/jface/text/tests/contentassist/FilteringAsyncContentAssistTests.java
org.eclipse.jface.text.tests/src/org/eclipse/jface/text/tests/contentassist/IncrementalAsyncContentAssistTests.java

Fixed test that didn't created Display but disposed it.
See https://github.com/eclipse-platform/eclipse.platform.ui/issues/50

Address "Device is disposed" error after test execution #50

---

org.eclipse.jface.text/src/org/eclipse/jface/internal/text/InformationControlReplacer.java

This is a fix for [Bug 562709](https://bugs.eclipse.org/bugs/show_bug.cgi?id=562709) - Focused quick fix popup doesn't properly layout quick fix options. 
The problem arises from the fact that some IInformationControl implementations need a size constraint set in order to properly layout themselves when an input is set, but the size of the shell needed to show a given content may change based on input (because the toolbar in the status row of the popup in this instance gets filled based on the input).
The fix consist of first setting a size constraint, then setting the input, and then computing the size again with the input set.
Invoke the various information controls that can be replaced (i.e. that can take focus and become resizable) and make sure the contents are properly displayed in …

Bug 562709: Fix layout for focused quickfix popup

---

org.eclipse.core.filebuffers.tests/pom.xml
org.eclipse.jface.text.examples/pom.xml
org.eclipse.jface.text.tests/pom.xml
org.eclipse.search.tests/pom.xml
org.eclipse.text.quicksearch.tests/pom.xml
org.eclipse.text.tests/pom.xml
org.eclipse.ui.editors.tests/pom.xml
org.eclipse.ui.genericeditor.tests/pom.xml
org.eclipse.ui.workbench.texteditor.tests/pom.xml
pom.xml
tests-pom/pom.xml

Tracked in [eclipse.platform.releng.aggregator#290](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/290) and [eclipse.platform.releng.aggregator#291](https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/291)
Need to wait to merge until after 4.24 Release

WIP: POM and product version changes for 4.25 release

---

Jenkinsfile

Tracked eclipse-platform/eclipse.platform.releng.aggregator#293

Use Java 17 for verification build

---

org.eclipse.jface.text/META-INF/MANIFEST.MF

Needed by
https://github.com/eclipse-platform/eclipse.platform.text/issues/23

Version bump for 4.25 stream.

---

org.eclipse.search/search/org/eclipse/search/internal/core/text/TextSearchVisitor.java

see https://github.com/eclipse-platform/eclipse.platform.text/pull/30#issuecomment-1185512753

Fix NPE when searching in open file which is linked multiple times

---

org.eclipse.search/new search/org/eclipse/search/ui/text/AbstractTextSearchResult.java

Fixes https://github.com/eclipse-platform/eclipse.platform.text/issues/63

Don't fail on null keys (#63)

---

org.eclipse.ui.workbench.texteditor/src/org/eclipse/ui/texteditor/AbstractTextEditor.java

Avoids "Unhandled event loop exception" log entry.

Do not log OperationCanceledException on user cancel (fixes #65)

---

org.eclipse.jface.text/src/org/eclipse/jface/contentassist/IContentAssistSubjectControl.java
org.eclipse.jface.text/src/org/eclipse/jface/text/contentassist/IContentAssistProcessor.java
org.eclipse.jface.text/src/org/eclipse/jface/text/formatter/ContextBasedFormattingStrategy.java
org.eclipse.jface.text/src/org/eclipse/jface/text/formatter/IContentFormatterExtension.java
org.eclipse.search/new search/org/eclipse/search/ui/text/AbstractTextSearchViewPage.java
org.eclipse.text/src/org/eclipse/jface/text/IDocumentPartitioningListener.java
org.eclipse.text/src/org/eclipse/jface/text/source/IAnnotationMap.java

As found by Java 17 javadoc tool.
Needed by
eclipse-platform/eclipse.platform.releng.aggregator#482

Fix Javadoc warnings and errors.

---

org.eclipse.core.filebuffers.tests/pom.xml
org.eclipse.jface.text.examples/pom.xml
org.eclipse.jface.text.tests/pom.xml
org.eclipse.search.tests/pom.xml
org.eclipse.text.quicksearch.tests/pom.xml
org.eclipse.text.tests/pom.xml
org.eclipse.ui.editors.tests/pom.xml
org.eclipse.ui.genericeditor.tests/pom.xml
org.eclipse.ui.workbench.texteditor.tests/pom.xml
pom.xml
tests-pom/pom.xml

Tracked in
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/514

Opening of 4 26 stream for development

---

org.eclipse.ui.genericeditor/META-INF/MANIFEST.MF
org.eclipse.ui.genericeditor/src/org/eclipse/ui/internal/genericeditor/compare/GenericEditorMergeViewer.java

Use EditorUI preferences in TextMergeViewer with GenericEditor
Signed-off-by: azerr <azerr@redhat.com>

Use EditorUI preferences in TextMergeViewer with GenericEditor

---

org.eclipse.jface.text.tests/src/org/eclipse/jface/text/tests/contentassist/AsyncContentAssistTest.java
org.eclipse.jface.text.tests/src/org/eclipse/jface/text/tests/contentassist/DelayedErrorContentAssistProcessor.java

forceFocus() seem to be not reliable that the control receives the key
event.

try to fix AsyncContentAssistTest.testCompleteActivationChar() #35

---

org.eclipse.jface.text/src/org/eclipse/jface/text/link/LinkedModeUI.java

The Linked Editing is to be disabled on Undo operatioin, otherwise some extra characters
may be removed/inserted by Undo operation.
Fixes: https://github.com/eclipse/lsp4e/issues/178
Change-Id: I51a921caa482262b0a73a73dba709e554f428a80
Signed-off-by: Victor Rubezhny <vrubezhny@redhat.com>

Undo operation fails to correctly restore text

---

org.eclipse.ui.genericeditor.examples/META-INF/MANIFEST.MF

Bundles need resigning for
https://github.com/eclipse-platform/eclipse.platform.releng.aggregator/issues/661

Version bump for 4.26 stream.

---

org.eclipse.ui.genericeditor/schema/foldingReconcilers.exsd
org.eclipse.ui.genericeditor/schema/highlightReconcilers.exsd
org.eclipse.ui.genericeditor/schema/reconcilers.exsd
org.eclipse.ui.genericeditor/src/org/eclipse/ui/internal/genericeditor/ExtensionBasedTextViewerConfiguration.java
org.eclipse.ui.genericeditor/src/org/eclipse/ui/internal/genericeditor/GenericContentTypeRelatedExtension.java
org.eclipse.ui.genericeditor/src/org/eclipse/ui/internal/genericeditor/ReconcilerRegistry.java

Register IReconcilingStrategy with GenericEditor extension point.
Fixes #115

Register IReconcilingStrategy with GenericEditor extension point.

---

org.eclipse.jface.text/src/org/eclipse/jface/text/source/SourceViewer.java

Keep the same order of install / uninstall than before.
Signed-off-by: azerr <azerr@redhat.com>

Keep the same order of install / uninstall than before.

---

org.eclipse.jface.text/src/org/eclipse/jface/text/source/inlined/AbstractInlinedAnnotation.java
org.eclipse.jface.text/src/org/eclipse/jface/text/source/inlined/InlinedAnnotationSupport.java

Example for https://github.com/eclipse-platform/eclipse.platform.swt/pull/67

Example usage of display executor

---

org.eclipse.text.quicksearch/META-INF/MANIFEST.MF
org.eclipse.text.quicksearch/src/org/eclipse/text/quicksearch/internal/core/LineItem.java

- add code to find innermost project file for a LineItem
- fixes #31

Fix duplicate entries in QuickSearch dialog for nested projects

---

org.eclipse.search/META-INF/MANIFEST.MF
org.eclipse.search/search/org/eclipse/search/internal/ui/text/FileSearchPage.java

Fixes https://github.com/eclipse-platform/eclipse.platform.text/issues/141

Search View: also open most nested resource on 2nd open

---

org.eclipse.search/META-INF/MANIFEST.MF
org.eclipse.search/search/org/eclipse/search/internal/ui/text/ReplaceRefactoring.java

Get rid of O(n^2) compares during search&replace with hashing.

ReplaceRefactoring: improve performance

---

org.eclipse.ui.workbench.texteditor/src/org/eclipse/ui/internal/views/minimap/MinimapWidget.java

Minimap can cause NPE #69
Consolidation for NPE avoidance

Minimap can cause NPE #69

---

org.eclipse.ui.genericeditor - Copy/src/org/eclipse/ui/internal/genericeditor/messages.properties
org.eclipse.ui.genericeditor/plugin.xml
org.eclipse.ui.genericeditor/src/org/eclipse/ui/internal/genericeditor/ExtensionBasedTextEditor.java
org.eclipse.ui.genericeditor/src/org/eclipse/ui/internal/genericeditor/GotoMatchingBracketHandler.java
org.eclipse.ui.genericeditor/src/org/eclipse/ui/internal/genericeditor/Messages.java

Go To Matching bracket support

Go To Matching bracket support

---

Jenkinsfile
org.eclipse.jface.text.tests/META-INF/MANIFEST.MF
org.eclipse.jface.text.tests/src/org/eclipse/jface/text/tests/contentassist/ContextInformationTest.java

Trying to get rid of CentOS 7 image building.

Update Jenkinsfile to build using CentOS 8

---

org.eclipse.ui.editors/src/org/eclipse/ui/internal/editors/text/codemining/annotation/AnnotationCodeMiningFilter.java

Fixes https://github.com/eclipse-platform/eclipse.platform.text/issues/173

Avoid NPE when annotation.getText() == null

---

org.eclipse.text.quicksearch/META-INF/MANIFEST.MF
org.eclipse.text.quicksearch/src/org/eclipse/text/quicksearch/internal/ui/QuickSearchPreferencesPage.java

This is a continuation of https://github.com/eclipse-platform/eclipse.platform.text/pull/133.
I did not know how to push a second commit to the existing pr #133 .

Fix alignment of preference field labels

---

org.eclipse.search/search/org/eclipse/search/internal/ui/text/FileTreeContentProvider.java

- add filtering to FileTreeContentProvider.elementsChanged() method so extraneous line elements are already filtered out of lineMatches set
- fixes #187

Fix UI freeze when searching

---

org.eclipse.jface.text/src/org/eclipse/jface/text/contentassist/AsyncCompletionProposalPopup.java

This reverts commit 783721b4f298b29f2f69f6d763623f52b32bf9b5.
The created ForkJoinPool are never shutdown which result in a memory leak. 
See #190

Revert "Use a custom ForkJoinWorkerThreadFactory in AsyncCompletionProposalPopup (#185)"

---

org.eclipse.jface.text/src/org/eclipse/jface/internal/text/html/BrowserInformationControl.java

Adds internal API to dispose browser hovers that stay closed for long.
Fixes: #191

Add internal API to dispose browser hovers that stay closed for long

---

org.eclipse.jface.text.tests/src/org/eclipse/jface/text/tests/contentassist/AbstractContentAssistTest.java
org.eclipse.jface.text.tests/src/org/eclipse/jface/text/tests/contentassist/AsyncContentAssistTest.java
org.eclipse.jface.text.tests/src/org/eclipse/jface/text/tests/contentassist/ContextInformationPresenterTest.java
org.eclipse.jface.text.tests/src/org/eclipse/jface/text/tests/contentassist/ContextInformationTest.java
org.eclipse.ui.genericeditor.tests/META-INF/MANIFEST.MF
org.eclipse.ui.genericeditor.tests/src/org/eclipse/ui/genericeditor/tests/CompletionTest.java
org.eclipse.ui.genericeditor.tests/src/org/eclipse/ui/genericeditor/tests/TestQuickAssist.java

Identify correct shell instead of taking random one.

fix ContextInformationTest #35

---

org.eclipse.ui.editors/META-INF/MANIFEST.MF
org.eclipse.ui.editors/src/org/eclipse/ui/internal/editors/text/AnnotationsConfigurationBlock.java
org.eclipse.ui.editors/src/org/eclipse/ui/internal/editors/text/LinkedModeConfigurationBlock.java

see
https://stackoverflow.com/questions/8777257/equals-vs-arrays-equals-in-java

Compare Array content instead of instance comparison

---

org.eclipse.jface.text/src/org/eclipse/jface/text/source/ChangeRulerColumn.java
org.eclipse.search.tests/META-INF/MANIFEST.MF
org.eclipse.search.tests/src/org/eclipse/search/tests/filesearch/FileCharSequenceTests.java

Add missing "static" modifier for constants

---

org.eclipse.core.filebuffers.tests/META-INF/MANIFEST.MF
org.eclipse.core.filebuffers.tests/src/org/eclipse/core/filebuffers/tests/ConvertLineDelemiterTest.java
org.eclipse.core.filebuffers/META-INF/MANIFEST.MF
org.eclipse.core.filebuffers/src/org/eclipse/core/internal/filebuffers/FileStoreTextFileBuffer.java
org.eclipse.core.filebuffers/src/org/eclipse/core/internal/filebuffers/ResourceTextFileBuffer.java
org.eclipse.text.quicksearch/META-INF/MANIFEST.MF
org.eclipse.text.quicksearch/src/org/eclipse/text/quicksearch/internal/core/QuickTextSearcher.java
org.eclipse.text.quicksearch/src/org/eclipse/text/quicksearch/internal/util/LineReader.java
org.eclipse.ui.editors/src/org/eclipse/ui/editors/text/StorageDocumentProvider.java
org.eclipse.ui.editors/src/org/eclipse/ui/internal/editors/quickdiff/LastSaveReferenceProvider.java

Doesn't try to fix anything. Just code and warnings reduced.

Use try-with-resource and java.io.InputStream convenience methods

---

org.eclipse.search/META-INF/MANIFEST.MF
org.eclipse.search/new search/org/eclipse/search/ui/text/AbstractTextSearchViewPage.java

remainder of layoutFlags % 2 < 0 for layoutFlags < 0

fix AbstractTextSearchViewPage.countBits

---

org.eclipse.ui.genericeditor/src/org/eclipse/ui/internal/genericeditor/folding/IndentFoldingStrategy.java

[GenericEditor] An NPE hoccurs in IndentFoldingStrategy.reconcile #228

---

org.eclipse.core.filebuffers/src/org/eclipse/core/internal/filebuffers/ResourceTextFileBuffer.java

Unused private member warning as visible at
https://download.eclipse.org/eclipse/downloads/drops4/I20230616-1800/compilelogs/plugins/org.eclipse.core.filebuffers_3.8.100.v20230616-0753/@dot.html#OTHER_WARNINGS .
While at it some further modernization of the code like using pattern matching and properly ordering modifiers according to JLS

Fix warnings in I-build

---

org.eclipse.ui.editors/src/org/eclipse/ui/internal/editors/text/codemining/annotation/AnnotationCodeMining.java
org.eclipse.ui.editors/src/org/eclipse/ui/internal/editors/text/codemining/annotation/AnnotationCodeMiningFilter.java
org.eclipse.ui.editors/src/org/eclipse/ui/internal/editors/text/codemining/annotation/AnnotationCodeMiningProvider.java

AnnotationCodeMining: remove Unnecessary @SuppressWarnings("null")
