org.eclipse.text/META-INF/MANIFEST.MF
org.eclipse.text/src/org/eclipse/jface/text/source/AnnotationModel.java

AnnotationModel.fAnnotations is deprecated and getAnnotationMap() should
be used instead.
However I still see the code that uses AnnotationModel.fAnnotations
inside AnnotationModel, even together with the getAnnotationMap(). This
should be fixed as precondition to fix of inefficient map iterations
inside same class.
https://github.com/eclipse-platform/eclipse.platform.text/issues/19

AnnotationModel uses both fAnnotations and getAnnotationMap() (Fixes #19)

---

org.eclipse.search/META-INF/MANIFEST.MF
org.eclipse.search/search/org/eclipse/search/internal/core/text/FileCharSequenceProvider.java
org.eclipse.search/search/org/eclipse/search/internal/core/text/TextSearchVisitor.java
org.eclipse.search/search/org/eclipse/search/internal/ui/text/FileSearchQuery.java

* Read each file only once (if it fits in the buffers) => ~ 30% faster
* Immediate report search result while still searching => faster visible
* Share workload between threads to avoid that single job with huge file
is running much longer then the others => faster finished.
* Set current filename as job name => better progress report.

Improve FileSearch performance (fixes #29)

---

org.eclipse.jface.text.tests/pom.xml
org.eclipse.search.tests/pom.xml
org.eclipse.ui.editors.tests/pom.xml
org.eclipse.ui.genericeditor.tests/pom.xml
org.eclipse.ui.workbench.texteditor.tests/pom.xml

Bug for which this was workaround is not needed for long time.
Change-Id: Idc77b384e172cc2bda93f8df3c523e16a0d3c9b5

Remove useless test requirement on org.eclipse.equinox.event

---

org.eclipse.text/META-INF/MANIFEST.MF
org.eclipse.text/src/org/eclipse/jface/text/source/AnnotationModel.java

This reverts commit db6a3b4064f214e154956130197bc73aff082708 because
this change may cause inconsistent model state in case of parallel
operations on the annotations map (key set iterator was working on a
snapshot, but entry set is not).
See discussion on
https://github.com/eclipse-platform/eclipse.platform.text/pull/22

Revert "AnnotationModel uses inefficient iteration over map (Reopens #21)"

---

org.eclipse.search/search/org/eclipse/search/internal/core/text/TextSearchVisitor.java

- Allow to cancel between(!) files and
- after the first(!) (and every 20th) hit inside a file.
see https://bugs.eclipse.org/bugs/show_bug.cgi?id=541178

Bug 541178 - Cancel during file search

---

org.eclipse.ui.editors/META-INF/MANIFEST.MF
org.eclipse.ui.editors/plugin.properties
org.eclipse.ui.editors/plugin.xml
org.eclipse.ui.editors/src/org/eclipse/ui/internal/editors/text/TextEditorDefaultsPreferencePage.java

This reverts changes made for bug
https://bugs.eclipse.org/bugs/show_bug.cgi?id=488162 which were made
because of concerns related to the performance of the Zoom in/Zoom Out
and scroll operations in huge text files with word wrap enabled (see
details in https://bugs.eclipse.org/bugs/show_bug.cgi?id=484142).
6 years and few releases later (4.6 -> 4.25) I can't observe significant
issues anymore, so let user decide if the word wrap should be always
enabled or not on opening editors (it can still be switched off).
Fixes https://github.com/eclipse-platform/eclipse.platform.text/issues/67

Unhide "enable word wrap" global preference UI (#67)

---

org.eclipse.search/search/org/eclipse/search/internal/ui/text/FileSearchQuery.java

Searching for pattern 'searchtext' instead of '\Qsearchtext\E'

Improve Search progress text to show human readable text

---

org.eclipse.search/META-INF/MANIFEST.MF
org.eclipse.search/search/org/eclipse/search/internal/core/text/TextSearchVisitor.java
org.eclipse.search/search/org/eclipse/search/internal/ui/SearchMessages.java
org.eclipse.search/search/org/eclipse/search/internal/ui/SearchMessages.properties

File search did not cancel it's worker jobs if the user canceled before
the monitorUpdateJob was running (scheduling it is no guarantee that is
already running).
* monitor job is now incorporated into the search thread.
* fixed expected number of files to scan
* do not exit search thread before all workers finished.
* cancel search if any of the workers canceled
* forward cancel immediately (do not wait 100ms)

File search: Reliable and fast cancel

---

org.eclipse.search/META-INF/MANIFEST.MF
org.eclipse.search/new search/org/eclipse/search/ui/text/FileTextSearchScope.java

If same search is started in parallel.
java.util.regex.Matcher is not thread-safe.

fix StringIndexOutOfBoundsException during File Search #79

---

org.eclipse.text/META-INF/MANIFEST.MF
org.eclipse.text/src/org/eclipse/jface/text/AbstractLineTracker.java

Change that introduced DocumentRewriteSession was not thread safe.
Code that modified document via set() or replace() in parallel with other thread working in startRewriteSession()/startRewriteSession()/flushRewriteSession() could run in troubles.

Make AbstractLineTracker thread safe (#91)

---

org.eclipse.jface.text/META-INF/MANIFEST.MF
org.eclipse.jface.text/src/org/eclipse/jface/internal/text/codemining/CodeMiningLineHeaderAnnotation.java

fResolvedMinings is filled only after draw.

fix CodeMiningProjectionViewerTest.testCodeMiningDoesntAlterFocus() #34

---

org.eclipse.jface.text.tests/src/org/eclipse/jface/text/tests/contentassist/AsyncContentAssistTest.java

testSyncFailureNPE failed because of late event handling

fix testCompleteActivationChar to not fail other test #75

---

org.eclipse.jface.text/src/org/eclipse/jface/text/link/LinkedModeUI.java

IDocumentUndoManager is not always registered for a document. DocumentUndoManagerRegistry.getDocumentUndoManager() can return null, don't unconditionally dereference return value.
See https://github.com/eclipse-platform/eclipse.platform.text/issues/33

Fixes for 24 new test fails in jdt.text.tests

---

org.eclipse.jface.text/META-INF/MANIFEST.MF
org.eclipse.jface.text/src/org/eclipse/jface/text/link/LinkedModeUI.java

Previous change on LinkedModeUI.doExit actually added some API and should have triggered a version bump (but wasn't detected by API Tools).

Bump o.e.jface.text version to 3.22

---

org.eclipse.jface.text/.settings/.api_filters

An API was effectively added, LinkedModeUI$IExitPolicy.doExit, but some other filter are necessary and make API tool miss this

Filter out org.eclipse.jface.text version warning

---

org.eclipse.jface.text.tests/META-INF/MANIFEST.MF
org.eclipse.jface.text.tests/src/org/eclipse/jface/text/tests/contentassist/ContextInformationTest.java

After https://github.com/eclipse-platform/eclipse.platform.swt/pull/451 focusing widget in a Shell that is not focused does nothing.
The test created new shells, and focused a button from original one - this doesn't work anymore. Fix the test to focus the expected shell first.
See https://github.com/eclipse-platform/eclipse.platform.swt/issues/502

Test fix: focus shell before focusing button

---

org.eclipse.jface.text.tests/src/org/eclipse/jface/text/tests/contentassist/ContextInformationTest.java

This reverts commit 01906e9811dcfde3a1c1a995230c4ef5dd0a216b as the original SWT change was reverted too via
https://github.com/eclipse-platform/eclipse.platform.swt/pull/503.

Revert "Test fix: focus shell before focusing button"

---

org.eclipse.jface.text/src/org/eclipse/jface/internal/text/codemining/CodeMiningLineHeaderAnnotation.java

- fix CodeMiningLineHeaderAnnotation to add check for mining label being empty
- fixes #131

Fix problem with empty code minings being shown

---

org.eclipse.search/search/org/eclipse/search/internal/ui/SearchMessages.java
org.eclipse.search/search/org/eclipse/search/internal/ui/SearchMessages.properties
org.eclipse.search/search/org/eclipse/search/internal/ui/text/FileSearchPage.java
org.eclipse.search/search/org/eclipse/search/internal/ui/text/FileSearchResult.java
org.eclipse.search/search/org/eclipse/search/internal/ui/text/FileTableContentProvider.java
org.eclipse.search/search/org/eclipse/search/internal/ui/text/FileTreeContentProvider.java
org.eclipse.search/search/org/eclipse/search/internal/ui/text/OuterProjectFileFilter.java

- add filter to File Search to remove duplicate file entries that are attributed to different projects in a nested project scenario
- fixes #143

Add filtering support for duplicate files in nested projects

---

org.eclipse.ui.genericeditor.tests/META-INF/MANIFEST.MF
org.eclipse.ui.genericeditor.tests/src/org/eclipse/ui/genericeditor/tests/FoldingTest.java

folding
The folding provider is going to become more reactive, so we improve it a bit
to allow async folding info.

Improve Generic Editor FoldingTest so it can handle async change to

---

org.eclipse.ui.genericeditor/META-INF/MANIFEST.MF
org.eclipse.ui.genericeditor/src/org/eclipse/ui/internal/genericeditor/ExtensionBasedTextViewerConfiguration.java
org.eclipse.ui.genericeditor/src/org/eclipse/ui/internal/genericeditor/folding/IndentFoldingStrategy.java

This enables folding in the generic text editor if the contributed folding reconciler cannot be applied e.g. LSP server does not provide folding support. Folding settings of several reconcilers will be applied to the viewer.
Background: see [LSP4E issue 410](https://github.com/eclipse/lsp4e/issues/410)

add always default folding reconciler

---

org.eclipse.search/search/org/eclipse/search/internal/core/text/TextSearchVisitor.java

- TextSearchVisitor.TextSearchJob.processFile() has a catch for FileCharSequenceProvider.FileCharSequenceException and tries to rethrow the exception cause.  In the case where the cause is an IOException, throw the original FileCharSequenceException which is a RuntimeException
- discovered by https://github.com/eclipse-jdt/eclipse.jdt.ui/issues/436

Fix ClassCastException in TextSearchVisitor.TextSearchJob

---

org.eclipse.jface.text/src/org/eclipse/jface/text/source/AnnotationRulerColumn.java

See https://bugs.eclipse.org/bugs/show_bug.cgi?id=531952 for original issue.
The code (text change listener) that was added to AnnotationRulerColumn to fix bug 531952 can be simply commented out without any visible regression.
Let's remove this code, it adds unneeded complexity & is inconsistent with the rest of the text listeners code that is supposed to be used from UI thread only.
Fixes https://github.com/eclipse-platform/eclipse.platform.text/issues/177

Remove AnnotationRulerColumn code added for bug 531952

---

org.eclipse.jface.text/src/org/eclipse/jface/text/source/MatchingCharacterPainter.java

`MatchingCharacterPainter` is using the `StyledText.getTextBounds()` method to determine the width of the highlight box to draw. This method calculates width based on runs of text, and thus includes the method parameter hints in that width.
This change instead moves to using `GC.textExtent()` to determine the width of text to highlight, ensuring that only the desired character is highlighted. The character width to highlight was already hard-coded to `1`, so now we just pull a single character of text from the desired offset, and pass it to `GC.textExtent()` to get its width.
**Manual testing**
Tested on Windows, running in a normal window
Tested on Windows, on a desktop with 200% font scaling enabled:
**Unit testing**
I didn't find existing unit tests for `MatchingCharacterPainter`, and …

brackets highlighting should not contains code mining text #47

---

org.eclipse.jface.text/src/org/eclipse/jface/text/contentassist/AsyncCompletionProposalPopup.java

Fix bug a introduced in 78fc9f6f6566323c691f1fee1eb14de2f27e7d34 that prevented the popup from closing when there are were completions left.
In addition, create the variable stillComputing earlier so that it can be reused.

Hide the popup in async mode when there are no completions left

---

org.eclipse.jface.text/src/org/eclipse/jface/text/contentassist/AsyncCompletionProposalPopup.java

CompletableFuture.supplyAsync() is using the defaultForkJoinWorkerThreadFactory. In case a SecurityManager is installed, using the defaultForkJoinWorkerThreadFactory would result in worker threads with no permissions, which leads to not content assist in the java editor.
Use a custom ForkJoinWorkerThreadFactory implementation to work around this.
See also:
https://github.com/eclipse-platform/eclipse.platform/issues/294
https://github.com/eclipse-platform/eclipse.platform/pull/295
1. Have any Eclipse-plugin that installs a SecurityManager. Use attached demo plugin [foo.bar.securitymanager.zip](https://github.com/eclipse-platform/eclipse.platform/files/10208024/foo.bar.securitymanager.zip) (Main Menu SecurityManager -> Install SecurityManager) or the following snippet:
``` …
```

Use a custom ForkJoinWorkerThreadFactory in AsyncCompletionProposalPopup

---

org.eclipse.jface.text/src/org/eclipse/jface/text/contentassist/AsyncCompletionProposalPopup.java

the last remaining proposal computation finishes.
Instead the tear down is done either when it was not visible (as before #183) or when it was visible but there is no proposals to show.

Reverts #183, as it causes the PopupVisibleTimer to be kept running when

---

org.eclipse.ui.genericeditor/META-INF/MANIFEST.MF
org.eclipse.ui.genericeditor/src/org/eclipse/ui/internal/genericeditor/GenericEditorContentAssistant.java

Both the JDT and VSCode do not trigger auto completion on each alphanumeric character by default. They only do it on trigger characters and only with a delay of 10 milliseconds.
This PR change the configuration of the Generic Editor to have the same defaults

Use less aggressive defaults

---

org.eclipse.ui.genericeditor/src/org/eclipse/ui/internal/genericeditor/hover/CompositeInformationControl.java

Avoiding type-casts makes code easier to read.

Use typed for-each loop

---

org.eclipse.ui.genericeditor/plugin.properties

Add the missing label and description for the _Go to Matching Bracket_ command

"Go to Matching Bracket" command: add missing label and description
